### ISSUE TITLE
Upgrade expo example to latest Expo

### ISSUE THREAD

**Issue by cmacdonnacha** [Noitidart/react-native-popup-menu-android#1]
Hey,

Would you mind upgrading the expo sdk version so I can run the app?
https://snack.expo.io/@noitsnack/react-native-popup-menu-android-demo

Thanks!

**Comment by SiyabongaNzulwana** [comment]
How do you pass the ref to a custom component?

**Comment by Noitidart** [comment]
Expo version updated! Thanks for noting this!

**Comment by Noitidart** [comment]
> 
> 
> How do you pass the ref to a custom component?

What do you mean @SiyabongaNzulwana ? Can you show me your custom component and I'll show you how to use it.
